# Database Configuration
database:
  url: postgresql://aut_str_user:aut_str_password@localhost:5432/aut_str_db

cookie:
  expiry_days: 0.001  # Очень короткий срок жизни cookie (около 1.5 минут)
  key: superstrongkey
  name: demo_cookie


